"""
ghlib — tiny procedural-modeling toolkit for Gloamhollow's Blender assets.

Every model in the game is generated by Python scripts that run inside
Blender (or the `bpy` module).  This file holds the shared helpers so all
assets share one look: chunky low-poly shapes, slightly jittered vertices,
per-face colour variation, fake baked AO and a muted, dark palette.

Conventions
-----------
* Units are metres.  Blender is Z-up; the glTF exporter converts to Y-up.
* Models stand on the ground at the origin.  "Front" faces Blender -Y,
  which becomes +Z in three.js.
* Colours are written as FLOAT_COLOR face-corner attributes (linear).  The
  palette below is authored in sRGB and converted on write.
* Material slots (by name) tell the game how to shade a face:
    Mat_Base   - ordinary vertex-coloured surface
    Mat_Leaves - foliage; tinted by season and swayed by wind in-game
    Mat_Emit   - self-lit (flames, eyes, runes); feeds the bloom pass
    Mat_Metal  - slightly metallic / shiny
* Animated characters are hierarchies of rigid parts named body, head,
  arm_l, arm_r, leg_l, leg_r (+ optional extras) whose origins sit at the
  joints.  Sockets (hand_r, light, door, ...) are empties.
"""
import math
import random

import bpy  # must come first: the bpy wheel registers bmesh/mathutils on import
import bmesh
from mathutils import Euler, Matrix, Quaternion, Vector

# ---------------------------------------------------------------------------
# Palette (sRGB 0-1).  Dark, desaturated, Nordic.
# ---------------------------------------------------------------------------
def hexc(h):
    h = h.lstrip('#')
    return tuple(int(h[i:i + 2], 16) / 255.0 for i in (0, 2, 4))


P = {
    # woods
    'bark':        hexc('#5a4331'),
    'bark_dark':   hexc('#3a2a1f'),
    'birch':       hexc('#c9c4b6'),
    'birch_mark':  hexc('#2b2724'),
    'wood':        hexc('#6b4d33'),
    'wood_light':  hexc('#8a6a47'),
    'wood_dark':   hexc('#3b2a1d'),
    'wood_grey':   hexc('#5b5550'),
    # foliage
    'pine':        hexc('#2b4632'),
    'pine_light':  hexc('#3b5a3c'),
    'leaf':        hexc('#4c6a2d'),
    'leaf_light':  hexc('#6a8a3a'),
    'leaf_dark':   hexc('#314a22'),
    'moss':        hexc('#48582a'),
    'grass':       hexc('#4f6b2c'),
    'straw':       hexc('#a08a52'),
    'thatch':      hexc('#7d6a3f'),
    'turf':        hexc('#3f5226'),
    # stone & earth
    'stone':       hexc('#6a6b6b'),
    'stone_light': hexc('#8c8c88'),
    'stone_dark':  hexc('#3e4042'),
    'slate':       hexc('#474d55'),
    'soil':        hexc('#3b2b1f'),
    'soil_wet':    hexc('#261b14'),
    'sand':        hexc('#9c8b69'),
    'copper':      hexc('#b06a3b'),
    'copper_ore':  hexc('#4f8f7a'),
    'iron':        hexc('#595e63'),
    'iron_dark':   hexc('#34383c'),
    'bronze':      hexc('#9a6a33'),
    'gold':        hexc('#d8a441'),
    'silver':      hexc('#b9bcc0'),
    'coal':        hexc('#1c1c1e'),
    # fabrics & materials
    'wool':        hexc('#bdb3a0'),
    'linen':       hexc('#d6ccb4'),
    'leather':     hexc('#5e3b22'),
    'leather_dk':  hexc('#3b2616'),
    'red':         hexc('#7a2219'),
    'red_dark':    hexc('#4e1712'),
    'blue':        hexc('#2d3f5a'),
    'blue_dark':   hexc('#1c273a'),
    'green':       hexc('#35492b'),
    'teal':        hexc('#2b5250'),
    'purple':      hexc('#44304f'),
    'ochre':       hexc('#a8792e'),
    'black':       hexc('#171615'),
    'white':       hexc('#e8e4da'),
    'bone':        hexc('#d9d0b8'),
    'bone_dark':   hexc('#a79c80'),
    'rust':        hexc('#7c4a2a'),
    'rope':        hexc('#8b7650'),
    # fur & feathers
    'fur_brown':   hexc('#6e4f36'),
    'fur_grey':    hexc('#77746e'),
    'fur_dark':    hexc('#2c2a28'),
    'fur_white':   hexc('#ddd6c8'),
    'fur_fox':     hexc('#b4592a'),
    'fur_cream':   hexc('#e3cfa8'),
    'feather_blk': hexc('#1e1f26'),
    'feather_owl': hexc('#8a7153'),
    'beak':        hexc('#c9a24a'),
    'skin':        hexc('#c9a386'),
    'eye':         hexc('#0e0d0c'),
    # crops & food
    'turnip':      hexc('#e3d7c9'),
    'turnip_top':  hexc('#8a4b8f'),
    'carrot':      hexc('#d9782d'),
    'onion':       hexc('#c89a5a'),
    'pumpkin':     hexc('#d4762a'),
    'beet':        hexc('#6d1830'),
    'barley':      hexc('#c9a95c'),
    'flax':        hexc('#6f86b8'),
    'nightshade':  hexc('#3a1f55'),
    'frost':       hexc('#9fd4e8'),
    'berry_red':   hexc('#a3202a'),
    'berry_blue':  hexc('#2f3f8f'),
    'mushroom':    hexc('#b3312a'),
    'mush_yellow': hexc('#d4a93a'),
    'mush_stem':   hexc('#e0d6c0'),
    # emissive (these go on Mat_Emit faces)
    'fire':        hexc('#ffb040'),
    'fire_hot':    hexc('#ffe28a'),
    'ember':       hexc('#ff5a1a'),
    'glow_blue':   hexc('#7fd8ff'),
    'glow_green':  hexc('#9dff9a'),
    'glow_eye':    hexc('#ffd36b'),
    'glow_purple': hexc('#c38bff'),
    'rune':        hexc('#6fe0ff'),
}


def srgb_to_linear(c):
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def col(name_or_rgb, mul=1.0):
    """Palette lookup (or pass-through tuple), optionally brightness-scaled."""
    rgb = P[name_or_rgb] if isinstance(name_or_rgb, str) else name_or_rgb
    return tuple(min(1.0, max(0.0, v * mul)) for v in rgb)


def mix(a, b, t):
    a = col(a)
    b = col(b)
    return tuple(a[i] * (1 - t) + b[i] * t for i in range(3))


# ---------------------------------------------------------------------------
# Scene helpers
# ---------------------------------------------------------------------------
MATERIAL_NAMES = ['Mat_Base', 'Mat_Leaves', 'Mat_Emit', 'Mat_Metal']
MAT_INDEX = {'base': 0, 'leaves': 1, 'emit': 2, 'metal': 3}


def reset_scene():
    """Remove every object/mesh/material so a script starts clean."""
    for ob in list(bpy.data.objects):
        bpy.data.objects.remove(ob, do_unlink=True)
    for me in list(bpy.data.meshes):
        bpy.data.meshes.remove(me)
    for ma in list(bpy.data.materials):
        bpy.data.materials.remove(ma)
    ensure_materials()


def ensure_materials():
    """Create the four shared materials (vertex-colour driven)."""
    mats = {}
    for name in MATERIAL_NAMES:
        m = bpy.data.materials.get(name)
        if m is None:
            m = bpy.data.materials.new(name)
            m.use_nodes = True
            nt = m.node_tree
            bsdf = nt.nodes.get('Principled BSDF')
            attr = nt.nodes.new('ShaderNodeVertexColor')
            attr.layer_name = 'Col'
            nt.links.new(attr.outputs['Color'], bsdf.inputs['Base Color'])
            bsdf.inputs['Roughness'].default_value = 0.85
            if name == 'Mat_Metal':
                bsdf.inputs['Metallic'].default_value = 0.6
                bsdf.inputs['Roughness'].default_value = 0.45
            if name == 'Mat_Emit':
                nt.links.new(attr.outputs['Color'], bsdf.inputs['Emission Color'])
                bsdf.inputs['Emission Strength'].default_value = 3.0
        mats[name] = m
    return mats


def empty(name, loc=(0, 0, 0), parent=None):
    """Create an empty (used for roots and sockets).  `loc` is in world space."""
    ob = bpy.data.objects.new(name, None)
    ob.empty_display_size = 0.15
    bpy.context.scene.collection.objects.link(ob)
    set_parent(ob, parent, Vector(loc))
    return ob


def world_origin(ob):
    """World-space origin of an object built by this library (no rotation)."""
    p = Vector((0, 0, 0))
    while ob is not None:
        p += ob.location
        ob = ob.parent
    return p


def set_parent(ob, parent, world_loc):
    if parent is not None:
        ob.parent = parent
        ob.location = Vector(world_loc) - world_origin(parent)
    else:
        ob.location = Vector(world_loc)


def descendants(ob):
    out = [ob]
    for c in ob.children:
        out.extend(descendants(c))
    return out


# ---------------------------------------------------------------------------
# Mesh builder
# ---------------------------------------------------------------------------
def _matrix(loc=(0, 0, 0), rot=(0, 0, 0), scale=(1, 1, 1)):
    if isinstance(scale, (int, float)):
        scale = (scale, scale, scale)
    S = Matrix.Diagonal((scale[0], scale[1], scale[2], 1.0))
    R = Euler(tuple(math.radians(a) for a in rot), 'XYZ').to_matrix().to_4x4()
    T = Matrix.Translation(Vector(loc))
    return T @ R @ S


class Builder:
    """Accumulates primitives into one bmesh with colours + material ids.

    Every primitive method takes:
        loc, rot (degrees XYZ), scale  - placement in model space
        color   - palette key or rgb tuple (sRGB)
        mat     - 'base' | 'leaves' | 'emit' | 'metal'
        jitter  - random vertex displacement in metres
        var     - per-face brightness variation (0.06 default)
    and returns the list of new faces (rarely needed).
    """

    def __init__(self, seed=1):
        self.bm = bmesh.new()
        self.col_layer = self.bm.loops.layers.float_color.new('Col')
        self.rng = random.Random(seed)

    # -- internals -------------------------------------------------------
    def _finish(self, verts, color, mat, jitter, var, smooth=False):
        verts = list(verts)
        faces = set()
        for v in verts:
            faces.update(v.link_faces)
        # stable order so colour variation is identical on every rebuild
        self.bm.faces.index_update()
        faces = sorted(faces, key=lambda f: f.index)
        verts.sort(key=lambda v: (v.co.x, v.co.y, v.co.z))
        if jitter:
            moved = set()
            for v in verts:
                if v in moved:
                    continue
                moved.add(v)
                v.co += Vector((self.rng.uniform(-jitter, jitter),
                                self.rng.uniform(-jitter, jitter),
                                self.rng.uniform(-jitter, jitter)))
        base = col(color)
        for f in faces:
            k = 1.0 + self.rng.uniform(-var, var)
            tint = [self.rng.uniform(-var * 0.35, var * 0.35) for _ in range(3)]
            c = tuple(min(1.0, max(0.0, base[i] * k + tint[i] * base[i])) for i in range(3))
            lin = tuple(srgb_to_linear(x) for x in c) + (1.0,)
            for loop in f.loops:
                loop[self.col_layer] = lin
            f.material_index = MAT_INDEX[mat]
            f.smooth = smooth
        return list(faces)

    # -- primitives ------------------------------------------------------
    def box(self, size=(1, 1, 1), loc=(0, 0, 0), rot=(0, 0, 0), color='wood',
            mat='base', jitter=0.0, var=0.06, bevel=0.0):
        if isinstance(size, (int, float)):
            size = (size, size, size)
        M = _matrix(loc, rot, size)
        before = set(self.bm.faces) if bevel > 0 else None
        res = bmesh.ops.create_cube(self.bm, size=1.0, matrix=M)
        verts = res['verts']
        if bevel > 0:
            edges = set()
            for v in verts:
                edges.update(v.link_edges)
            bmesh.ops.bevel(self.bm, geom=list(edges), offset=bevel,
                            segments=1, affect='EDGES', profile=0.5)
            # bevel replaces the cube's verts, so gather what is new instead
            verts = set()
            for f in self.bm.faces:
                if f not in before:
                    verts.update(f.verts)
        return self._finish(verts, color, mat, jitter, var)

    def cyl(self, r1=0.5, r2=None, h=1.0, seg=8, loc=(0, 0, 0), rot=(0, 0, 0),
            scale=(1, 1, 1), color='wood', mat='base', jitter=0.0, var=0.06,
            cap=True, smooth=False):
        """Cylinder/cone standing on `loc` (base at loc, extends +Z by h)."""
        if r2 is None:
            r2 = r1
        M = _matrix(loc, rot, scale) @ Matrix.Translation((0, 0, h / 2))
        res = bmesh.ops.create_cone(self.bm, cap_ends=cap, cap_tris=False,
                                    segments=seg, radius1=r1, radius2=r2,
                                    depth=h, matrix=M)
        return self._finish(res['verts'], color, mat, jitter, var, smooth)

    def cone(self, r=0.5, h=1.0, seg=8, **kw):
        return self.cyl(r1=r, r2=0.0, h=h, seg=seg, **kw)

    def sphere(self, r=0.5, seg=8, rings=6, loc=(0, 0, 0), rot=(0, 0, 0),
               scale=(1, 1, 1), color='stone', mat='base', jitter=0.0,
               var=0.06, smooth=False):
        M = _matrix(loc, rot, scale)
        res = bmesh.ops.create_uvsphere(self.bm, u_segments=seg,
                                        v_segments=rings, radius=r, matrix=M)
        return self._finish(res['verts'], color, mat, jitter, var, smooth)

    def ico(self, r=0.5, sub=1, loc=(0, 0, 0), rot=(0, 0, 0), scale=(1, 1, 1),
            color='stone', mat='base', jitter=0.0, var=0.06, smooth=False,
            flatten_below=None):
        """Icosphere; `flatten_below` clamps verts below that model-space z."""
        M = _matrix(loc, rot, scale)
        res = bmesh.ops.create_icosphere(self.bm, subdivisions=sub, radius=r,
                                         matrix=M)
        faces = self._finish(res['verts'], color, mat, jitter, var, smooth)
        if flatten_below is not None:
            for v in res['verts']:
                if v.co.z < flatten_below:
                    v.co.z = flatten_below
        return faces

    def lathe(self, profile, seg=10, loc=(0, 0, 0), rot=(0, 0, 0),
              scale=(1, 1, 1), color='wood', mat='base', jitter=0.0,
              var=0.06, smooth=False, cap_bottom=True, cap_top=True):
        """Revolve a profile [(radius, z), ...] (bottom->top) around Z."""
        M = _matrix(loc, rot, scale)
        rings = []
        verts = []
        for (r, z) in profile:
            ring = []
            for i in range(seg):
                a = 2 * math.pi * i / seg
                if r <= 1e-6:
                    ring = [self.bm.verts.new(M @ Vector((0, 0, z)))]
                    break
                ring.append(self.bm.verts.new(M @ Vector((r * math.cos(a), r * math.sin(a), z))))
            rings.append(ring)
            verts.extend(ring)
        for k in range(len(rings) - 1):
            a, b = rings[k], rings[k + 1]
            for i in range(seg):
                if len(a) == 1 and len(b) == 1:
                    continue
                if len(a) == 1:
                    # bottom fan: wind so the faces point outward
                    self.bm.faces.new((a[0], b[(i + 1) % seg], b[i]))
                elif len(b) == 1:
                    self.bm.faces.new((a[i], a[(i + 1) % seg], b[0]))
                else:
                    self.bm.faces.new((a[i], a[(i + 1) % seg], b[(i + 1) % seg], b[i]))
        if cap_bottom and len(rings[0]) > 2:
            self.bm.faces.new(list(reversed(rings[0])))
        if cap_top and len(rings[-1]) > 2:
            self.bm.faces.new(rings[-1])
        return self._finish(verts, color, mat, jitter, var, smooth)

    def tube(self, points, radii, seg=6, color='bark', mat='base', jitter=0.0,
             var=0.06, cap=True):
        """Chain of tapered cylinders through `points` (model space)."""
        faces = []
        if isinstance(radii, (int, float)):
            radii = [radii] * len(points)
        for i in range(len(points) - 1):
            a = Vector(points[i])
            b = Vector(points[i + 1])
            d = b - a
            L = d.length
            if L < 1e-6:
                continue
            q = Vector((0, 0, 1)).rotation_difference(d.normalized())
            M = Matrix.Translation(a) @ q.to_matrix().to_4x4() @ Matrix.Translation((0, 0, L / 2))
            res = bmesh.ops.create_cone(self.bm, cap_ends=cap, cap_tris=False,
                                        segments=seg, radius1=radii[i],
                                        radius2=radii[i + 1], depth=L, matrix=M)
            faces += self._finish(res['verts'], color, mat, jitter, var)
        return faces

    def quad(self, corners, color='wood', mat='base', var=0.06, double=False):
        """Single polygon from 3+ model-space corners (CCW = front)."""
        vs = [self.bm.verts.new(Vector(c)) for c in corners]
        self.bm.faces.new(vs)
        faces = self._finish(vs, color, mat, 0.0, var)
        if double:
            vs2 = [self.bm.verts.new(Vector(c)) for c in reversed(corners)]
            self.bm.faces.new(vs2)
            faces += self._finish(vs2, color, mat, 0.0, var)
        return faces

    def prism(self, outline, h, loc=(0, 0, 0), rot=(0, 0, 0), color='wood',
              mat='base', jitter=0.0, var=0.06):
        """Extrude a 2D outline [(x, y), ...] (CCW) upward by h."""
        M = _matrix(loc, rot, (1, 1, 1))
        bot = [self.bm.verts.new(M @ Vector((x, y, 0))) for (x, y) in outline]
        top = [self.bm.verts.new(M @ Vector((x, y, h))) for (x, y) in outline]
        n = len(outline)
        self.bm.faces.new(list(reversed(bot)))
        self.bm.faces.new(top)
        for i in range(n):
            j = (i + 1) % n
            self.bm.faces.new((bot[i], bot[j], top[j], top[i]))
        return self._finish(bot + top, color, mat, jitter, var)

    def rock(self, r=0.5, loc=(0, 0, 0), scale=(1, 1, 0.7), color='stone',
             sub=1, jitter=None, var=0.1, sink=0.15):
        """Chunky boulder sitting on the ground (bottom flattened)."""
        if jitter is None:
            jitter = r * 0.22
        lz = loc[2] + r * scale[2] * (1 - sink)
        return self.ico(r=r, sub=sub, loc=(loc[0], loc[1], lz), scale=scale,
                        color=color, jitter=jitter, var=var,
                        flatten_below=loc[2])

    # -- output ----------------------------------------------------------
    def build(self, name, origin=(0, 0, 0), parent=None, ao=0.25, ao_floor=None):
        """Create the mesh object.  `origin` (model space) becomes its pivot.

        ao: fake ambient occlusion - faces near the object's bottom are
        darkened by up to this fraction (0 disables).
        """
        bm = self.bm
        if ao and len(bm.faces):
            zs = [v.co.z for v in bm.verts]
            z0 = min(zs) if ao_floor is None else ao_floor
            z1 = max(zs)
            span = max(1e-3, z1 - z0)
            for f in bm.faces:
                if f.material_index == MAT_INDEX['emit']:
                    continue
                t = (f.calc_center_median().z - z0) / span
                k = 1.0 - ao * (1.0 - min(1.0, max(0.0, t)) ** 0.6)
                for loop in f.loops:
                    c = loop[self.col_layer]
                    loop[self.col_layer] = (c[0] * k, c[1] * k, c[2] * k, 1.0)
        o = Vector(origin)
        for v in bm.verts:
            v.co -= o
        bmesh.ops.remove_doubles(bm, verts=bm.verts, dist=1e-5)
        bm.normal_update()
        me = bpy.data.meshes.new(name)
        bm.to_mesh(me)
        bm.free()
        self.bm = None
        # compact material slots to the ones actually used
        mats = ensure_materials()
        used = sorted({p.material_index for p in me.polygons})
        remap = {old: new for new, old in enumerate(used)}
        for old in used:
            me.materials.append(mats[MATERIAL_NAMES[old]])
        for p in me.polygons:
            p.material_index = remap[p.material_index]
        me.color_attributes.active_color_name = 'Col'
        me.color_attributes.render_color_index = 0
        ob = bpy.data.objects.new(name, me)
        bpy.context.scene.collection.objects.link(ob)
        set_parent(ob, parent, o)
        return ob


# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------
def export_glb(path, roots):
    """Export the given root objects (and their children) to one .glb file."""
    for ob in bpy.context.scene.objects:
        ob.select_set(False)
    for r in roots:
        for d in descendants(r):
            d.select_set(True)
    bpy.ops.export_scene.gltf(
        filepath=path,
        export_format='GLB',
        use_selection=True,
        export_yup=True,
        export_apply=True,
        export_texcoords=False,
        export_normals=True,
        export_vertex_color='ACTIVE',
        export_all_vertex_colors=False,
        export_materials='EXPORT',
        export_extras=True,
        export_animations=False,
        export_cameras=False,
        export_lights=False,
    )


def stats(roots):
    """Return {root_name: triangle_count} for a quick budget check."""
    out = {}
    for r in roots:
        tris = 0
        for d in descendants(r):
            if d.type == 'MESH':
                for p in d.data.polygons:
                    tris += len(p.vertices) - 2
        out[r.name] = tris
    return out
